### ISSUE TITLE
Corcurrency problem in JsPool _metadata

### ISSUE THREAD

**Issue by huan086** [Daniel15/JSPool#13]
Potentially related issues

https://github.com/reactjs/React.NET/issues/251
https://github.com/Daniel15/JSPool/issues/12
https://github.com/Daniel15/JSPool/issues/11

As mentioned in https://github.com/reactjs/React.NET/issues/251:

JavaScriptEngineFactory is registered as singleton. JavaScriptEngineFactory has JsPool. Thus, JsPool is singleton. JsPool has Dictionary _metadata, which is not thread-safe. Access to _metadata in CreateEngine, TakeEngine, ReturnEngineToPool and DisposeEngine do not use any synchronization, thus potentially modifying _metadata from different threads and corrupting it.

Switching to ConcurrentDictionary should solve the issue. Additionally, this._engineCount should be replaced by _metadata.Count in order to get a consistent count to prevent race condition.

Race condition: consider where engine is released and requested from different thread, one thread releases, the other request, but fails at this.EngineCount < this._config.MaxEngines due to this.EngineCount not being decrement yet.

**Comment by huan086** [comment]
Problem was introduced by commit be7edbf on 2015-02-22, where ConcurrentBag was changed to Dictionary.

**Comment by huan086** [comment]
This test fails intermittently, confirming concurrency issue.

https://github.com/huan086/JSPool/commit/d3d8094d2a63bad056c2fcb43fd41189e1dbceae

**Comment by Daniel15** [comment]
Good catch! I didn't think that `_metadata` had to be thread-safe but it seems like that assumption is incorrect. Thanks for the unit test, I'll fix this soon :)

**Comment by Daniel15** [comment]
Thanks for the but report. You were right - Switching to `ConcurrentDictionary` fixed the issue. I also added your test :)

**Comment by Daniel15** [comment]
Pushed 0.3.2 with this fix.
