### ISSUE TITLE
`MsieJsEngine` and `JsEngineWithOwnThread` wrapper

### ISSUE THREAD

**Issue by Taritsyn** [Daniel15/JSPool#20]
Starting with the [MSIE JavaScript Engine 2.1.0](https://github.com/Taritsyn/MsieJavaScriptEngine/releases/tag/v2.1.0) and [JavaScript Engine Switcher 2.2.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v2.2.0) in `MsieJsEngine` (and in `ChakraCoreJsEngine`) solved the problem with the “Out of stack space” error. Therefore, it is possible to abandon the joint usage of `MsieJsEngine` and `JsEngineWithOwnThread` wrapper.

**Comment by Daniel15** [comment]
Hey @Taritsyn, thanks for letting me know. The reason I was using `JsEngineWithOwnThread` was because the MSIE engine can only be used from a single thread, so I can't reuse the engine across multiple threads. Do you solve this in the MSIE JavaScript Engine library?

**Comment by Taritsyn** [comment]
> ... I can't reuse the engine across multiple threads.

I use the MSIE JavaScript Engine on a single thread by using a [`ScriptDispatcher`](https://github.com/Taritsyn/MsieJavaScriptEngine/blob/master/src/MsieJavaScriptEngine/ScriptDispatcher.cs) class. According to the principle of action it is similar to your solution, only I use a lower-level synchronization tools.

In ActiveScript modes all instances of engines are used in a single thread. In addition, it was possible to abandon the usage of a `System.Windows.Threading.Dispatcher` class from `WindowsBase` assembly.

In JsRT modes each instance of engine is created and used in own separate thread.

**Comment by Daniel15** [comment]
Released in 3.0
