### ISSUE TITLE
Binding redirect needed due to dependency on 2.4.9

### ISSUE THREAD

**Issue by mvestergaard** [Daniel15/JSPool#25]
Hi Daniel,

Would it be possible for you to change you dependency on JavaScriptEngineSwitcher.Core to >= 2.4.0.0 so it aligns with the various engine implementations.

Currently it results in these types of messages during build:
```
  No way to resolve conflict between "JavaScriptEngineSwitcher.Core, Version=2.4.9.0, Culture=neutral, PublicKeyToken=c608b2a8cc9e4472" and "JavaScriptEngineSwitcher.Core, Version=2.4.0.0, Culture=neutral, PublicKeyToken=c608b2a8cc9e4472". Choosing "JavaScriptEngineSwitcher.Core, Version=2.4.9.0, Culture=neutral, PublicKeyToken=c608b2a8cc9e4472" arbitrarily.
  Consider app.config remapping of assembly "JavaScriptEngineSwitcher.Core, Culture=neutral, PublicKeyToken=c608b2a8cc9e4472" from Version "2.4.9.0" [] to Version "2.4.10.0" [C:\Source\Roadmap\master2\Nis.WebControls\bin\Release\JavaScriptEngineSwitcher.Core.dll] to solve conflict and get rid of warning.
```

The issue is that our solution consists of many applications, and the reference to JavaScriptEngineSwitcher.Core is in a core library, so we would need to add the binding redirect all over the place

**Comment by Daniel15** [comment]
> Would it be possible for you to change you dependency on JavaScriptEngineSwitcher.Core to >= 2.4.0.0 so it aligns with the various engine implementations.

I don't think that'd help as you'll still have issues if an engine references a newer version of `JavaScriptEngineSwitcher.Core` than JSPool does. Assembly references do not support ranges like `>= 2.4.0.0`, that's only a NuGet concept.

You can add a binding redirect to your `app.config` or `web.config` to resolve the conflict. Additionally, .NET Framework 4.5.1 and above support automatic assembly binding redirects: https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection

**Comment by mvestergaard** [comment]
You're probably right. I'm trying to find a different solution to the problem.
