### ISSUE TITLE
JsPool recycle is not thread safe

### ISSUE THREAD

**Issue by benokit** [Daniel15/JSPool#36]
JsPool.Recycle() method is not thread safe because DisposeAllEngines() is not thread safe:
It clears the  _availableEngines first and _metadata next. But in a concurrent environment it can happen that _availableEngines will not be empty when _metadata gets cleared. Consequently, when trying to get an engine whose metadata was cleared we will get an error:

> {"Message":"The given key was not present in the dictionary.","Code":null,"StackTrace":" at 
> System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key) at 
> JSPool.JsPool`2.TakeEngine(TPooled engine) at JSPool.JsPool`2.GetEngine(Nullable`1 timeout) 

Check the simulation of this scenario in a unit test: https://github.com/benokit/JSPool/blob/master/tests/JSPool.Tests/JsPoolRecycleTests.cs

Possible solution:

Remove _metadata entirely. Add EngineMetada property to PooledObject<T> class.

**Comment by Daniel15** [comment]
Good catch!

The easiest thing is probably to take a lock in that function, although removing _metadata entirely is possible now that we have the PooledObject class (which didn't used to exist). Would you like to submit a pull request to fix this?

**Comment by benokit** [comment]
Thanks for the quick response. I will prepare a pull request.

**Comment by benokit** [comment]
@Daniel15, here is the pool request: https://github.com/Daniel15/JSPool/pull/37.

I didn't go with the "lock" solution. It is not that simple. You would have to use the same lock object for three branches of execution: recyle, create engine and return engine, which means that "create engine" and "return engine" would undesirably lock each other. Moreover, because _availableEngines is protected you don't have control of how it will be (ab)used in the derived class.

**Comment by Daniel15** [comment]
Thank you for the pull request! :)
