### ISSUE TITLE
Have option to set heap size via V8RuntimeConstraints?

### ISSUE THREAD

**Issue by PeteDuncanson** [Daniel15/JSPool#4]
In the docs for clearscript I noticed you can pass in a constraints object that lets you set the memory size that you are happy for the runtime to get up to.

Noticed in this thread that they no longer recommend using it however it might still be useful in a pooled environment (hoping @Daniel15 will know more about this than me) so flagging it up as a nice to know.

https://clearscript.codeplex.com/discussions/572036

**Comment by Daniel15** [comment]
JavaScriptEngineSwitcher supports these in the Web.config or App.config now, similar to #5. Example:
```
<v8 disableGlobalMembers="true" maxExecutableSize="..." maxNewSpaceSize="..." maxOldSpaceSize="..." />
```
