### ISSUE TITLE
Have option to disable host variables

### ISSUE THREAD

**Issue by PeteDuncanson** [Daniel15/JSPool#5]
Found that if you use the V8Runtime.CreateScriptEngine method for spinning up a new engine context you can pass in options to disable allowing calls out to the .net host environment or variables. This should give a "significant" performance boost apparently. Might help with https://github.com/Daniel15/JSPool/issues/3

See Microsoft.ClearScript.V8.V8ScriptEngineFlags Enumeration

Option DisableGlobalMembers - Specifies that support for GlobalMembers behavior is to be disabled. This option yields a significant performance benefit for global item access. 

For reference GlobalMembers - Defines options for exposing host resources to script code.

**Comment by Daniel15** [comment]
Looks like JavaScriptEngineSwitcher added support for `DisableGlobalMembers` in version 1.2.3: https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/master/CHANGELOG.md

You may even be able to just set this in your Web.config or App.config file, if JavaScriptEngineSwitcher has implemented that.

**Comment by Daniel15** [comment]
Upgraded JavaScriptEngineSwitcher to the latest version in fd946d9c404f421a7cd7cc6aa5b0f581815419e5. This update allows you to set this flag in your Web.config or App.config:

```
<configuration>
	...
	<jsEngineSwitcher xmlns="http://tempuri.org/JavaScriptEngineSwitcher.Configuration.xsd">
		...
		<v8 disableGlobalMembers="true" />
	</jsEngineSwitcher>
```
